### ISSUE TITLE
Introduce JSONCompareMode

### ISSUE THREAD

**Issue by nyszilard** [karsaig/approvalcrest#14]
It would be great if we could set the way the comparison works in assertThat, as in the **skyscreamer/JSONassert** lib. It is very annoying when a bean is extended with some other fields, and we have to regenerate the approved files. It's a very bad practice, and there is a potential danger that our old tests will no longer test the same, because of the changed expected files. It is also time consuming when a lot of tests are involved.

### JSONCompareMode options:
- **LENIENT** Lenient checking. Extensible, and non-strict array ordering.
- **NON_EXTENSIBLE** Non-extensible checking. Not extensible, and non-strict array ordering.
- **STRICT** Strict checking. Not extensible, and strict array ordering.
- **STRICT_ORDER** Strict order checking. Extensible, and strict array ordering.

### The way it would work:
assertThat(actual, sameJsonAsApproved(), JSONCompareMode.LENINENT);

**Comment by karsaig** [comment]
Imo one of the benefits of using this tool instead of others is the strictness of it. Even not intended changes are visible on PRs for example. Which quite often contain bugs. In case verified bean changes, its natural the files representing its state also change. The moment leniency would be introduced, someone would have to check which changes are needed and which aren't, which is another possible source of error, and a possible source of bugs, which would no longer be caught.

>It is very annoying when a bean is extended with some other fields, and we have to regenerate the approved files.

I agree it is annoying, but its also one of the drawbacks of testing whole state. It can be mitigated by adding a CI job which rans the changes and produce a diff file, at least that is what we usually did on projects, and added simple tooling to make it easy to review these changes. There are plans to mitigate some of this in different ways, but neither will remove the need to update at least some files when tested object changes.

>It's a very bad practice, and there is a potential danger that our old tests will no longer test the same, because of the changed expected files. It is also time consuming when a lot of tests are involved.

Any change to approved files require review, as any change to expected values would also require review, no matter how they're represented. In order for an old test not to test the same, something else also has to change in the file, beside the trivial change of an added field (the given example). Which is equivalent of an expected value changing in a test. Without review it might break the test. Its always up to the developer and reviewers to make sure the expectations are correct. With added leniency, making sure they are, probably would require more mental work. As currently a trivial field addition causes the same trivial change in every file, which is quick and easy to review.

>It is also time consuming when a lot of tests are involved.

Agreed, I'll look into open sourcing the tools we've added around this, but that'll only help with reviewing the changes, will not remove them.

So mitigating above mentioned problems is possible, but adding lenient mode would be a step in the wrong direction imo.
